### ISSUE TITLE
关于协程内存消耗数量的疑问

### ISSUE THREAD

**Issue by yuanzhubi** [tearshark/librf#1]
“创建100万个协程只需使用<820M>物理内存”
这个应该看使用的局部变量消耗的空间的大小？还是说除开了局部变量在堆上的”持久化保存“，其他的所有消耗在820M 左右？

**Comment by tearshark** [comment]
那次测试并没有特别精确的统计内存使用。而是通过操作系统观察到的内存占用。
因此，应该说是调度器所使用的内存，加上全部协程的局部变量保存在堆上使用的内存空间。
