### ISSUE TITLE
llvm clang11兼容性

### ISSUE THREAD

**Issue by xiamr** [tearshark/librf#3]
使用clang11.0 编译出现如下的错误（clang10 无此编译错误） ，使用了gcc10.2 的libstdc++
In file included from /home/xxx/prog/librf/librf/librf.h:82:
In file included from /home/xxx/prog/librf/librf/src/mutex.h:5:
/home/xxx/prog/librf/librf/src/mutex_v2.inl:476:15: error: the expression 'co_await __promise.final_suspend()' is required to be non-throwing
                        future_t<> _Yield() const
                                   ^
/data/software/gcc-10.2.0/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/coroutine:205:5: note: must be declared with 'noexcept'
    }

**Comment by xiamr** [comment]
在gcc10.2头文件/data/software/gcc-10.2.0/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/coroutine的第200行的最后加上noexcept可以绕过这个编译错误，可能clang11相比clang10改变了对coroutine声明的要求

**Comment by tearshark** [comment]
在C++20的协程支持程度上，GCC编译器，以及GCC提供的头文件，都还存在一些问题。
